<?php

namespace kamaelkz\yii2admin\v1\widgets;

use Yii;
use yii\widgets\Breadcrumbs as Base;
use kamaelkz\yii2admin\v1\themes\components\view\View;

/**
 * Виджет хлебных крошек
 *
 * @author kamaelkz <kamaelkz@yandex.kz>
 */
class Breadcrumbs extends Base
{
    /**
     * @var bool
     */
    public $encodeLabels = false;

    /**
     * @var array
     */
    public $homeLink;

    /**
     * @var string
     */
    public $tag = 'div';

    /**
     * @var string
     */
    public $itemTemplate = "{link}";

    /**
     * @var string
     */
    public $itemClass = 'breadcrumb-item';

    /**
     * @var string
     */
    public $activeItemTemplate = "<span class=\"breadcrumb-item active\">{link}</span>";

    /**
     * @inheritDoc
     */
    public function beforeRun()
    {
        $view = $this->getView();
        if($view instanceof View) {
            $this->links = $view->getBreadcrumbs();
        }

        if (empty($this->homeLink)) {
            $this->homeLink = [
                'label' => '<i class="icon-home2 mr-2"></i> ' . Yii::t(yii2admin,'Главная'),
                'url' => Yii::$app->homeUrl,
                'type' => 'raw',
                'class' => $this->itemClass
            ];
        } else {
            $this->homeLink['class'] = $this->itemClass;
        }

        if(! empty($this->links)) {
            foreach ($this->links as &$link) {
                if (is_array($link)){
                    $link['class'] = $this->itemClass;
                }
            }
        }

        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }
}